/**
 * withBackendCertPinning.js
 *
 * Bundles the backend's (self-signed) TLS certificate into the Android
 * build and wires up a network security config that trusts it — scoped
 * only to the backend's own host(s), not app-wide. This is what makes the
 * app actually trust the server's HTTPS certificate on every tablet
 * automatically, without anyone having to manually install the cert as a
 * trusted CA on each device (which, on Android 7+, wouldn't even be
 * enough by itself — apps ignore user-installed CAs unless they opt in via
 * exactly this kind of config).
 *
 * Every other domain the app talks to (e.g. the cdnjs.cloudflare.com CDN
 * the PDF viewer's WebView loads pdf.js from) is left on Android's normal
 * default trust behavior — this only adds an extra trusted anchor for the
 * specific backend host(s), it doesn't relax anything else.
 *
 * Usage (app.json):
 *   "plugins": [
 *     ["./plugins/withBackendCertPinning", {
 *       "certPath": "./certs/backend-ca.pem",
 *       "hostnames": ["10.110.10.6"]
 *     }]
 *   ]
 *
 * See certs/README.md for how to swap in the real server certificate
 * before building for production.
 */

const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");

const RAW_RESOURCE_NAME = "backend_ca";
const NETWORK_SECURITY_CONFIG_NAME = "network_security_config";

function buildNetworkSecurityConfigXml(hostnames) {
    const domains = hostnames
        .map((host) => `        <domain includeSubdomains="false">${host}</domain>`)
        .join("\n");

    return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by withBackendCertPinning — do not hand-edit; it's overwritten
  on every prebuild/EAS build. Change the plugin options in app.json
  instead (certPath / hostnames).
-->
<network-security-config>
    <domain-config>
${domains}
        <trust-anchors>
            <!-- The backend's own (possibly self-signed) certificate -->
            <certificates src="@raw/${RAW_RESOURCE_NAME}"/>
            <!-- Also keep trusting normal public CAs for this host, so
                 nothing breaks if the backend later switches to a
                 properly CA-signed certificate instead of a self-signed one. -->
            <certificates src="system"/>
        </trust-anchors>
    </domain-config>
</network-security-config>
`;
}

/** Copies the cert into res/raw and writes the network security config XML into res/xml. */
function withBackendCertFiles(config, { certPath, hostnames }) {
    return withDangerousMod(config, [
        "android",
        async (config) => {
            const projectRoot = config.modRequest.projectRoot;
            const androidResPath = path.join(config.modRequest.platformProjectRoot, "app/src/main/res");

            const resolvedCertPath = path.resolve(projectRoot, certPath);
            if (!fs.existsSync(resolvedCertPath)) {
                throw new Error(
                    `[withBackendCertPinning] Certificate file not found: ${resolvedCertPath}. ` +
                        "See certs/README.md for how to generate/place it.",
                );
            }

            const rawDir = path.join(androidResPath, "raw");
            fs.mkdirSync(rawDir, { recursive: true });
            fs.copyFileSync(resolvedCertPath, path.join(rawDir, `${RAW_RESOURCE_NAME}.pem`));

            const xmlDir = path.join(androidResPath, "xml");
            fs.mkdirSync(xmlDir, { recursive: true });
            fs.writeFileSync(
                path.join(xmlDir, `${NETWORK_SECURITY_CONFIG_NAME}.xml`),
                buildNetworkSecurityConfigXml(hostnames),
            );

            return config;
        },
    ]);
}

/** Points the <application> tag at the network security config we just wrote. */
function withBackendCertManifest(config) {
    return withAndroidManifest(config, (config) => {
        const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
        mainApplication.$["android:networkSecurityConfig"] = `@xml/${NETWORK_SECURITY_CONFIG_NAME}`;
        return config;
    });
}

module.exports = function withBackendCertPinning(config, options = {}) {
    const certPath = options.certPath || "./certs/backend-ca.pem";
    const hostnames = options.hostnames || ["10.110.10.6"];

    if (!Array.isArray(hostnames) || hostnames.length === 0) {
        throw new Error("[withBackendCertPinning] `hostnames` must be a non-empty array");
    }

    config = withBackendCertFiles(config, { certPath, hostnames });
    config = withBackendCertManifest(config);
    return config;
};
