/**
 * withReleaseSigning.js
 *
 * android/ is regenerated by `expo prebuild` (it's gitignored — see
 * .gitignore's "generated native folders" section), so anything hand-edited
 * directly in android/app/build.gradle gets silently wiped the next time
 * prebuild runs. Expo's own template also ships with `release {
 * signingConfig signingConfigs.debug }` by default — meaning a plain
 * `gradlew assembleRelease`/`bundleRelease` produces a build signed with
 * the public Android debug key, which Google Play rejects outright.
 *
 * This plugin adds a real `release` signing config to build.gradle, keyed
 * off four environment variables read at prebuild time:
 *   RELEASE_KEYSTORE_PATH       absolute path to your .keystore/.jks file
 *   RELEASE_KEYSTORE_PASSWORD
 *   RELEASE_KEY_ALIAS
 *   RELEASE_KEY_PASSWORD
 *
 * None of these — nor the keystore file itself — should ever be committed
 * to the repo. Keep the keystore somewhere secure outside the project, and
 * set the four variables as persistent OS/user environment variables (or
 * export them in the shell before running prebuild), not in app.json or
 * any tracked file.
 *
 * If the env vars aren't set when prebuild runs, this plugin makes no
 * changes at all — the build falls back to Expo's normal debug-signed
 * release, so local/dev iteration keeps working exactly as before. Only a
 * prebuild run with all four variables present produces a properly
 * release-signed build.gradle.
 */

const { withGradleProperties, withAppBuildGradle } = require("expo/config-plugins");

const REQUIRED_ENV_VARS = [
    "RELEASE_KEYSTORE_PATH",
    "RELEASE_KEYSTORE_PASSWORD",
    "RELEASE_KEY_ALIAS",
    "RELEASE_KEY_PASSWORD",
];

function readReleaseSigningEnv() {
    const values = {};
    for (const key of REQUIRED_ENV_VARS) {
        const value = process.env[key];
        if (!value) return null; // any missing var -> not configured, skip entirely
        values[key] = value;
    }
    return values;
}

/** Writes the keystore path/passwords into android/gradle.properties, which
 * Gradle auto-exposes as bare project properties (e.g. MYAPP_RELEASE_STORE_FILE)
 * usable directly in build.gradle without any extra plumbing. */
function withReleaseGradleProperties(config, env) {
    return withGradleProperties(config, (config) => {
        const props = [
            { type: "property", key: "MYAPP_RELEASE_STORE_FILE", value: env.RELEASE_KEYSTORE_PATH },
            { type: "property", key: "MYAPP_RELEASE_STORE_PASSWORD", value: env.RELEASE_KEYSTORE_PASSWORD },
            { type: "property", key: "MYAPP_RELEASE_KEY_ALIAS", value: env.RELEASE_KEY_ALIAS },
            { type: "property", key: "MYAPP_RELEASE_KEY_PASSWORD", value: env.RELEASE_KEY_PASSWORD },
        ];
        config.modResults = config.modResults.filter(
            (item) => !(item.type === "property" && props.some((p) => p.key === item.key)),
        );
        config.modResults.push(...props);
        return config;
    });
}

/**
 * Adds a `release` signingConfig block guarded by
 * `project.hasProperty('MYAPP_RELEASE_STORE_FILE')`, and points
 * buildTypes.release at it when present — falling back to the existing
 * debug signingConfig otherwise, so an unconfigured environment still
 * builds (just not as something you'd upload to Play Console).
 */
function withReleaseSigningGradle(config) {
    return withAppBuildGradle(config, (config) => {
        let contents = config.modResults.contents;

        if (contents.includes("MYAPP_RELEASE_STORE_FILE")) {
            // Already injected by a previous prebuild pass over the same
            // file content — avoid inserting it twice.
            return config;
        }

        const debugSigningConfigBlock = /(signingConfigs\s*\{\s*debug\s*\{[\s\S]*?\n\s*\}\n)(\s*\})/;
        contents = contents.replace(debugSigningConfigBlock, (match, debugBlock, closingBrace) => {
            const releaseBlock =
                `        release {\n` +
                `            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {\n` +
                `                storeFile file(MYAPP_RELEASE_STORE_FILE)\n` +
                `                storePassword MYAPP_RELEASE_STORE_PASSWORD\n` +
                `                keyAlias MYAPP_RELEASE_KEY_ALIAS\n` +
                `                keyPassword MYAPP_RELEASE_KEY_PASSWORD\n` +
                `            }\n` +
                `        }\n`;
            return debugBlock + releaseBlock + closingBrace;
        });

        contents = contents.replace(
            /(release\s*\{\s*\n(?:\s*\/\/[^\n]*\n)*\s*signingConfig\s+)signingConfigs\.debug/,
            `$1project.hasProperty('MYAPP_RELEASE_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
        );

        config.modResults.contents = contents;
        return config;
    });
}

module.exports = function withReleaseSigning(config) {
    const env = readReleaseSigningEnv();

    if (!env) {
        console.warn(
            "[withReleaseSigning] RELEASE_KEYSTORE_PATH/RELEASE_KEYSTORE_PASSWORD/RELEASE_KEY_ALIAS/RELEASE_KEY_PASSWORD " +
                "are not all set — skipping release signing setup. The release build type will fall back to the debug " +
                "keystore, which Google Play will reject. Set these before running prebuild for a real production build.",
        );
        return config;
    }

    config = withReleaseGradleProperties(config, env);
    config = withReleaseSigningGradle(config);
    return config;
};
