/**
 * withBackendCertPinning.js
 *
 * Bundles the backend's (self-signed) TLS certificate into the Android
 * build and wires up a network security config that trusts it — scoped
 * only to the backend's own host(s), not app-wide. This is what makes the
 * app actually trust the server's HTTPS certificate on every tablet
 * automatically, without anyone having to manually install the cert as a
 * trusted CA on each device (which, on Android 7+, wouldn't even be
 * enough by itself — apps ignore user-installed CAs unless they opt in via
 * exactly this kind of config).
 *
 * Every other domain the app talks to (e.g. the cdnjs.cloudflare.com CDN
 * the PDF viewer's WebView loads pdf.js from) is left on Android's normal
 * default trust behavior — this only adds an extra trusted anchor for the
 * specific backend host(s), it doesn't relax anything else.
 *
 * ── Deploying before you have a TLS certificate ─────────────────────────
 * Since Android 9 (targetSdk 28+, which this project uses), plain HTTP is
 * BLOCKED by default unless a domain is explicitly marked
 * cleartextTrafficPermitted — without that, the app can't reach an
 * HTTP-only backend at all, it just fails with "CLEARTEXT communication
 * ... not permitted". EXPO_PUBLIC_BACKEND_USE_HTTPS is the single switch
 * for this, read here AND in src/config/env.ts, so both always agree:
 *   - unset / "false"  → cleartext HTTP permitted for these hostnames,
 *                        BASE_URL uses http://. No certificate needed yet.
 *   - "true"           → cleartext NOT permitted (Android's normal secure
 *                        default), BASE_URL uses https://, and the
 *                        bundled certificate is what makes that trusted.
 * Flip it to "true" once you have a real certificate in certs/ (see
 * certs/README.md), then rebuild — no other code changes needed.
 *
 * Usage (app.json):
 *   "plugins": [
 *     ["./plugins/withBackendCertPinning", {
 *       "certPath": "./certs/backend-ca.pem",
 *       "hostnames": ["10.110.10.6"]
 *     }]
 *   ]
 */

const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");

const RAW_RESOURCE_NAME = "backend_ca";
const NETWORK_SECURITY_CONFIG_NAME = "network_security_config";

function isHttpsEnabled() {
    return process.env.EXPO_PUBLIC_BACKEND_USE_HTTPS === "true";
}

function buildNetworkSecurityConfigXml(hostnames, allowCleartext) {
    const cleartextAttr = allowCleartext ? ' cleartextTrafficPermitted="true"' : "";
    const domains = hostnames
        .map((host) => `        <domain includeSubdomains="false">${host}</domain>`)
        .join("\n");

    return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by withBackendCertPinning — do not hand-edit; it's overwritten
  on every prebuild/EAS build. Change the plugin options in app.json, or
  EXPO_PUBLIC_BACKEND_USE_HTTPS, instead.
-->
<network-security-config>
    <domain-config${cleartextAttr}>
${domains}
        <trust-anchors>
            <!-- The backend's own (possibly self-signed) certificate.
                 Unused while cleartextTrafficPermitted is set above (no TLS
                 handshake happens over plain HTTP), harmless either way. -->
            <certificates src="@raw/${RAW_RESOURCE_NAME}"/>
            <!-- Also keep trusting normal public CAs for this host, so
                 nothing breaks if the backend later switches to a
                 properly CA-signed certificate instead of a self-signed one. -->
            <certificates src="system"/>
        </trust-anchors>
    </domain-config>
</network-security-config>
`;
}

/** Copies the cert into res/raw and writes the network security config XML into res/xml. */
function withBackendCertFiles(config, { certPath, hostnames }) {
    return withDangerousMod(config, [
        "android",
        async (config) => {
            const projectRoot = config.modRequest.projectRoot;
            const androidResPath = path.join(config.modRequest.platformProjectRoot, "app/src/main/res");

            const resolvedCertPath = path.resolve(projectRoot, certPath);
            if (!fs.existsSync(resolvedCertPath)) {
                throw new Error(
                    `[withBackendCertPinning] Certificate file not found: ${resolvedCertPath}. ` +
                        "See certs/README.md for how to generate/place it.",
                );
            }

            const rawDir = path.join(androidResPath, "raw");
            fs.mkdirSync(rawDir, { recursive: true });
            fs.copyFileSync(resolvedCertPath, path.join(rawDir, `${RAW_RESOURCE_NAME}.pem`));

            const xmlDir = path.join(androidResPath, "xml");
            fs.mkdirSync(xmlDir, { recursive: true });
            fs.writeFileSync(
                path.join(xmlDir, `${NETWORK_SECURITY_CONFIG_NAME}.xml`),
                buildNetworkSecurityConfigXml(hostnames, !isHttpsEnabled()),
            );

            return config;
        },
    ]);
}

/** Points the <application> tag at the network security config we just wrote. */
function withBackendCertManifest(config) {
    return withAndroidManifest(config, (config) => {
        const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
        mainApplication.$["android:networkSecurityConfig"] = `@xml/${NETWORK_SECURITY_CONFIG_NAME}`;
        return config;
    });
}

let hasLoggedMode = false;

module.exports = function withBackendCertPinning(config, options = {}) {
    const certPath = options.certPath || "./certs/backend-ca.pem";
    const hostnames = options.hostnames || ["10.110.10.6"];

    if (!Array.isArray(hostnames) || hostnames.length === 0) {
        throw new Error("[withBackendCertPinning] `hostnames` must be a non-empty array");
    }

    if (!isHttpsEnabled() && !hasLoggedMode) {
        hasLoggedMode = true;
        console.log(
            "[withBackendCertPinning] EXPO_PUBLIC_BACKEND_USE_HTTPS is not \"true\" — building for plain HTTP " +
                `(cleartext explicitly permitted for: ${hostnames.join(", ")}). Set it to "true" once you have a ` +
                "real TLS certificate, and rebuild.",
        );
    }

    config = withBackendCertFiles(config, { certPath, hostnames });
    config = withBackendCertManifest(config);
    return config;
};
